// Generated types for Supabase database schema
// This would normally be generated by: supabase gen types typescript

export interface Database {
  public: {
    Tables: {
      companies: {
        Row: {
          id: string;
          name: string;
          owner_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          owner_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          owner_id?: string | null;
          created_at?: string;
        };
      };
      users: {
        Row: {
          id: string;
          email: string;
          role: 'SUPERADMIN' | 'OWNER' | 'EMPLOYEE';
          company_id: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          email: string;
          role?: 'SUPERADMIN' | 'OWNER' | 'EMPLOYEE';
          company_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          role?: 'SUPERADMIN' | 'OWNER' | 'EMPLOYEE';
          company_id?: string | null;
          created_at?: string;
        };
      };
      modules: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          href: string | null;
          created_by: string;
          is_public_within_company: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          href?: string | null;
          created_by: string;
          is_public_within_company?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          href?: string | null;
          created_by?: string;
          is_public_within_company?: boolean;
          created_at?: string;
        };
      };
      invites: {
        Row: {
          id: string;
          token: string;
          email: string;
          role: 'OWNER' | 'EMPLOYEE';
          company_id: string;
          status: 'PENDING' | 'ACCEPTED' | 'EXPIRED';
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          token?: string;
          email: string;
          role?: 'OWNER' | 'EMPLOYEE';
          company_id: string;
          status?: 'PENDING' | 'ACCEPTED' | 'EXPIRED';
          expires_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          token?: string;
          email?: string;
          role?: 'OWNER' | 'EMPLOYEE';
          company_id?: string;
          status?: 'PENDING' | 'ACCEPTED' | 'EXPIRED';
          expires_at?: string;
          created_at?: string;
        };
      };
      users_modules: {
        Row: {
          user_id: string;
          module_id: string;
          granted_at: string;
        };
        Insert: {
          user_id: string;
          module_id: string;
          granted_at?: string;
        };
        Update: {
          user_id?: string;
          module_id?: string;
          granted_at?: string;
        };
      };
      company_modules: {
        Row: {
          company_id: string;
          module_id: string;
          is_enabled: boolean;
          created_at: string;
        };
        Insert: {
          company_id: string;
          module_id: string;
          is_enabled?: boolean;
          created_at?: string;
        };
        Update: {
          company_id?: string;
          module_id?: string;
          is_enabled?: boolean;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      get_user_role: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
      is_company_owner: {
        Args: {
          company_uuid: string;
        };
        Returns: boolean;
      };
    };
    Enums: {
  acceptInvite: (token: string, password: string) => Promise<void>;
  createInvite: (email: string, role: 'OWNER' | 'EMPLOYEE') => Promise<any>;
      [_ in never]: never;
    };
    contacts: {
      Row: {
        id: string;
        name: string;
        email: string | null;
        phone: string | null;
        company: string | null;
        title: string | null;
        skills: string[] | null;
        hourly_rate: number | null;
        availability: 'Available' | 'Busy' | 'Unavailable';
        notes: string | null;
        company_id: string;
        created_by: string;
        created_at: string;
        updated_at: string;
      };
      Insert: {
        id?: string;
        name: string;
        email?: string | null;
        phone?: string | null;
        company?: string | null;
        title?: string | null;
        skills?: string[] | null;
        hourly_rate?: number | null;
        availability?: 'Available' | 'Busy' | 'Unavailable';
        notes?: string | null;
        company_id: string;
        created_by: string;
        created_at?: string;
        updated_at?: string;
      };
      Update: {
        id?: string;
        name?: string;
        email?: string | null;
        phone?: string | null;
        company?: string | null;
        title?: string | null;
        skills?: string[] | null;
        hourly_rate?: number | null;
        availability?: 'Available' | 'Busy' | 'Unavailable';
        notes?: string | null;
        company_id?: string;
        created_by?: string;
        created_at?: string;
        updated_at?: string;
      };
    };
    clients: {
      Row: {
        id: string;
        client_number: number;
        company_name: string;
        start_date: string | null;
        end_date: string | null;
        business_type: string | null;
        employment_form: string | null;
        zus_details: string | null;
        zus_startup_relief: boolean;
        zus_startup_relief_months: number;
        tax_form: string | null;
        vat_status: string | null;
        vat_frequency: string | null;
        gtu_codes: string[] | null;
        vat_eu_registration: boolean;
        labor_fund: boolean;
        free_amount_2022: boolean;
        fixed_costs: string[] | null;
        vehicles_assets: string | null;
        depreciation_info: string | null;
        e_szok_system: boolean;
        has_employees: boolean;
        phone: string | null;
        email: string | null;
        database_status: string;
        aml_group: string | null;
        aml_date: string | null;
        service_provider: string | null;
        contract_status: string;
        annexes_2022_status: string | null;
        annexes_2022_sent_date: string | null;
        annexes_2023_status: string | null;
        annexes_2023_sent_date: string | null;
        additional_notes: string | null;
        company_id: string;
        created_by: string;
        created_at: string;
        updated_at: string;
      };
      Insert: {
        id?: string;
        client_number?: number;
        company_name: string;
        start_date?: string | null;
        end_date?: string | null;
        business_type?: string | null;
        employment_form?: string | null;
        zus_details?: string | null;
        zus_startup_relief?: boolean;
        zus_startup_relief_months?: number;
        tax_form?: string | null;
        vat_status?: string | null;
        vat_frequency?: string | null;
        gtu_codes?: string[] | null;
        vat_eu_registration?: boolean;
        labor_fund?: boolean;
        free_amount_2022?: boolean;
        fixed_costs?: string[] | null;
        vehicles_assets?: string | null;
        depreciation_info?: string | null;
        e_szok_system?: boolean;
        has_employees?: boolean;
        phone?: string | null;
        email?: string | null;
        database_status?: string;
        aml_group?: string | null;
        aml_date?: string | null;
        service_provider?: string | null;
        contract_status?: string;
        annexes_2022_status?: string | null;
        annexes_2022_sent_date?: string | null;
        annexes_2023_status?: string | null;
        annexes_2023_sent_date?: string | null;
        additional_notes?: string | null;
        company_id: string;
        created_by: string;
        created_at?: string;
        updated_at?: string;
      };
      Update: {
        id?: string;
        client_number?: number;
        company_name?: string;
        start_date?: string | null;
        end_date?: string | null;
        business_type?: string | null;
        employment_form?: string | null;
        zus_details?: string | null;
        zus_startup_relief?: boolean;
        zus_startup_relief_months?: number;
        tax_form?: string | null;
        vat_status?: string | null;
        vat_frequency?: string | null;
        gtu_codes?: string[] | null;
        vat_eu_registration?: boolean;
        labor_fund?: boolean;
        free_amount_2022?: boolean;
        fixed_costs?: string[] | null;
        vehicles_assets?: string | null;
        depreciation_info?: string | null;
        e_szok_system?: boolean;
        has_employees?: boolean;
        phone?: string | null;
        email?: string | null;
        database_status?: string;
        aml_group?: string | null;
        aml_date?: string | null;
        service_provider?: string | null;
        contract_status?: string;
        annexes_2022_status?: string | null;
        annexes_2022_sent_date?: string | null;
        annexes_2023_status?: string | null;
        annexes_2023_sent_date?: string | null;
        additional_notes?: string | null;
        company_id?: string;
        created_by?: string;
        created_at?: string;
        updated_at?: string;
      };
    };
    activity_logs: {
      Row: {
        id: string;
        user_id: string;
        company_id: string;
        action_type: 'created' | 'updated' | 'deleted' | 'enabled' | 'disabled';
        resource_type: 'module' | 'contact' | 'invite' | 'client';
        resource_name: string;
        details: Record<string, any>;
        created_at: string;
      };
      Insert: {
        id?: string;
        user_id: string;
        company_id: string;
        action_type: 'created' | 'updated' | 'deleted' | 'enabled' | 'disabled';
        resource_type: 'module' | 'contact' | 'invite' | 'client';
        resource_name: string;
        details?: Record<string, any>;
        created_at?: string;
      };
      Update: {
        id?: string;
        user_id?: string;
        company_id?: string;
        action_type?: 'created' | 'updated' | 'deleted' | 'enabled' | 'disabled';
        resource_type?: 'module' | 'contact' | 'invite' | 'client';
        resource_name?: string;
        details?: Record<string, any>;
        created_at?: string;
      };
    };
    price_list_items: {
      Row: {
        id: string;
        name: string;
        description: string | null;
        price: number;
        company_id: string;
        created_by: string;
        created_at: string;
      };
      Insert: {
        id?: string;
        name: string;
        description?: string | null;
        price: number;
        company_id: string;
        created_by: string;
        created_at?: string;
      };
      Update: {
        id?: string;
        name?: string;
        description?: string | null;
        price?: number;
        company_id?: string;
        created_by?: string;
        created_at?: string;
      };
    };
    offers: {
      Row: {
        id: string;
        client_id: string;
        net_total: number;
        status: 'DRAFT' | 'SENT' | 'ACCEPTED' | 'EXPIRED';
        accepted_at: string | null;
        token: string | null;
        company_id: string;
        created_by: string;
        created_at: string;
        updated_at: string;
      };
      Insert: {
        id?: string;
        client_id: string;
        net_total: number;
        status?: 'DRAFT' | 'SENT' | 'ACCEPTED' | 'EXPIRED';
        accepted_at?: string | null;
        token?: string | null;
        company_id: string;
        created_by: string;
        created_at?: string;
        updated_at?: string;
      };
      Update: {
        id?: string;
        client_id?: string;
        net_total?: number;
        status?: 'DRAFT' | 'SENT' | 'ACCEPTED' | 'EXPIRED';
        accepted_at?: string | null;
        token?: string | null;
        company_id?: string;
        created_by?: string;
        created_at?: string;
        updated_at?: string;
      };
    };
    offer_items: {
      Row: {
        id: string;
        offer_id: string;
        price_list_item_id: string | null;
        name: string;
        description: string | null;
        qty: number;
        price: number;
        line_total: number;
      };
      Insert: {
        id?: string;
        offer_id: string;
        price_list_item_id?: string | null;
        name: string;
        description?: string | null;
        qty: number;
        price: number;
      };
      Update: {
        id?: string;
        offer_id?: string;
        price_list_item_id?: string | null;
        name?: string;
        description?: string | null;
        qty?: number;
        price?: number;
      };
    };
    checklists: {
      Row: {
        id: string;
        client_id: string;
        title: string;
        description: string | null;
        is_completed: boolean;
        completed_at: string | null;
        completed_by: string | null;
        company_id: string;
        created_by: string;
        created_at: string;
        updated_at: string;
      };
      Insert: {
        id?: string;
        client_id: string;
        title: string;
        description?: string | null;
        is_completed?: boolean;
        completed_at?: string | null;
        completed_by?: string | null;
        company_id: string;
        created_by: string;
        created_at?: string;
        updated_at?: string;
      };
      Update: {
        id?: string;
        client_id?: string;
        title?: string;
        description?: string | null;
        is_completed?: boolean;
        completed_at?: string | null;
        completed_by?: string | null;
        company_id?: string;
        created_by?: string;
        created_at?: string;
        updated_at?: string;
      };
    };
  };
}

// Helper types for easier usage
export type User = Database['public']['Tables']['users']['Row'];
export type Company = Database['public']['Tables']['companies']['Row'];
export type Module = Database['public']['Tables']['modules']['Row'];
export type Client = Database['public']['Tables']['clients']['Row'];
export type Contact = Database['public']['Tables']['contacts']['Row'];
export type Invite = Database['public']['Tables']['invites']['Row'];
export type UserModule = Database['public']['Tables']['users_modules']['Row'];
export type ActivityLog = Database['public']['Tables']['activity_logs']['Row'];
export type PriceListItem = Database['public']['Tables']['price_list_items']['Row'];
export type Offer = Database['public']['Tables']['offers']['Row'];
export type OfferItem = Database['public']['Tables']['offer_items']['Row'];
export type Checklist = Database['public']['Tables']['checklists']['Row'];

// Role type for type safety
export type UserRole = 'SUPERADMIN' | 'OWNER' | 'EMPLOYEE';
export type InviteStatus = 'PENDING' | 'ACCEPTED' | 'EXPIRED';
export type ContactAvailability = 'Available' | 'Busy' | 'Unavailable';
export type OfferStatus = 'DRAFT' | 'SENT' | 'ACCEPTED' | 'EXPIRED';